name: Deploy team setup

on: [push, workflow_dispatch]

jobs:
  build-and-deploy:
    uses: LowerKees/ff_platform_automation/.github/workflows/separate-repos-platform-automation.yml@main
    with:
      configFilePath: team_001/config.json
      refCheckout: synapse-v1.0.0
    secrets:
      FF_AZ_CRED: ${{ secrets.FF_AZ_CRED}}
